version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: imc-rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # HTTP management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

